### ISSUE TITLE
info below ascii art disappeared after starting

### ISSUE THREAD

**Issue by shikon** [ndortega/Oxygen.jl#109]
After v1.1.8
![image](https://user-images.githubusercontent.com/33011458/235955099-48ae3e64-8dfa-43cb-b98f-25e4b3184a58.png)

expected:
![image](https://user-images.githubusercontent.com/33011458/235955358-69328f03-344b-45d2-a341-3cf7698e12be.png)

I haven't checked the tests but should've been caught there, maybe it is a local issue?

**Comment by shikon** [comment]
julia v1.8.5 on a windows machine. I run julia REPL through vscode.

**Comment by ndortega** [comment]
Does this issue happen on fresh projects? I also have the same setup

**Comment by shikon** [comment]
![image](https://user-images.githubusercontent.com/33011458/236426474-0a36043a-6083-4f51-b0a1-31298f90c47c.png)
No I guess it is local then...
