### ISSUE TITLE
Set caching headers for static content

### ISSUE THREAD

**Issue by sschmidhuber** [ndortega/Oxygen.jl#111]
Hello,

is there a way to set headers for static delivered content? I would like to set headers so that the client uses the browser cache for static assets `dynamicfiles` and `staticfiles`.

To my understanding that is currently not possible, is it?

BR Stefan

**Comment by ndortega** [comment]
Hi @sschmidhuber, 

You're correct that there's no built-in way to customize headers just for static file hosting, but you could create your own middleware function to do this. The middleware function below just manually checks to see if the `/static` path property exists inside the `request.target` property of the incoming `HTTP.Request`. 

To be fair, this was just the quickest solution I could think of to your problem. I could definitely look into adding some new inputs to those file hosting functions so we can customize the response objects. 

Here's my project structure:
<img width="270" alt="image" src="https://github.com/ndortega/Oxygen.jl/assets/22534471/5325947c-5af7-41fb-865d-e609a4a81e01">

And here's the sample module:
```julia
module CacheHeaderDemo

using Oxygen
using HTTP

@get "/" function()
    "hello world"
end

staticfiles("static")

function StaticFileMiddleware(handler)
    function(request::HTTP.Request)
        if contains(request.target, "/static")
            response = handler(request)
            HTTP.setheader(response, "My-Custom-Header" => "hello world")
        else 
            response = handler(request)
        end
        return response
    end
end

serve(middleware=[StaticFileMiddleware])

end
```

**Comment by sschmidhuber** [comment]
Cool that will work for me, thank you!

In the long run maybe passing optionally a header array to the `dynamicfiles` and `staticfiles` would be a solution.

**Comment by ndortega** [comment]
Hey @sschmidhuber, 

Sorry about the long wait, I have a PR open to address this issue. When you get a chance, take a look at the example and let me know what you think! Hopefully, this gives you the fine-grained control you wanted. 

Personally, I'm not sure if I went overboard providing the headers, route and mime type info to the callback function. Let me know if you think this is too much.

**Comment by ndortega** [comment]
Hi @sschmidhuber, I'm gonna close this issue now that I've merged the fix into the master branch

**Comment by sschmidhuber** [comment]
Hello @ndortega,
sorry for the delay, I was a bit occupied lately. I think the implementation via the callback function is a really nice solution, that should give all the flexibility one might need.

BR Stefan
