### ISSUE TITLE
IOError: write: broken pipe (EPIPE) error in Julia API running in Production (Kubernetes Cluster)

### ISSUE THREAD

**Issue by BrandonEscamilla** [ndortega/Oxygen.jl#114]
I am encountering an ﻿IOError: write: broken pipe (EPIPE) error in my Julia API, which only appears when running in Production (in a Kubernetes Cluster), I have never seen this issue in local. The error occurs randomly, sometimes breaking the session when making a request and sometimes not. I have tried several things to debug the issue, but I believe it is a core issue in either Oxygen or HTTP.jl.
Here are some details about my setup:

	•	Julia version: 1.9.0
	•	Oxygen version: 1.1.9
	•	HTTP.jl version: 1.9.6

The API is containerized and running in a Kubernetes cluster with adequate memory and vCPU resources allocated to the container. However, due to the nature of the application, some requests can be particularly resource-intensive, using a lot of memory. Despite the sufficient resources, I am encountering a ﻿IOError: write: broken pipe (EPIPE) error randomly when making requests to the API. To help diagnose the issue, I have attached the logs that are generated whenever this error occurs. Below you can find the logs I can see in Production: 

```
┌ Error: handle_connection handler error
│   exception =
│    IOError: write: broken pipe (EPIPE)
│    Stacktrace:
│      [1] uv_write(s::Sockets.TCPSocket, p::Ptr{UInt8}, n::UInt64)
│        @ Base ./stream.jl:1066
│      [2] unsafe_write(s::Sockets.TCPSocket, p::Ptr{UInt8}, n::UInt64)
│        @ Base ./stream.jl:1120
│      [3] unsafe_write
│        @ /home/.julia/packages/HTTP/uAaAw/src/Connections.jl:129 [inlined]
│      [4] write
│        @ ./strings/io.jl:244 [inlined]
│      [5] write
│        @ ./io.jl:678 [inlined]
│      [6] unsafe_write(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, p::Ptr{UInt8}, n::UInt64)
│        @ HTTP.Streams /home/.julia/packages/HTTP/uAaAw/src/Streams.jl:95
│      [7] write
│        @ ./strings/io.jl:244 [inlined]
│      [8] write(io::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, s::Base.CodeUnits{UInt8, String})
│        @ Base ./strings/basic.jl:761
│      [9] (::HTTP.Handlers.var"#1#2"{Oxygen.Core.var"#6#8"{Oxygen.Core.AutoDoc.var"#2#4"{Oxygen.Core.var"#28#31"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Vector{Function}}, Sockets.IPv4}})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│        @ HTTP.Handlers /home/.julia/packages/HTTP/uAaAw/src/Handlers.jl:61
│     [10] (::Oxygen.Core.var"#9#10"{Oxygen.Core.AutoDoc.var"#2#4"{Oxygen.Core.var"#28#31"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Vector{Function}}})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│        @ Oxygen.Core /home/.julia/packages/Oxygen/wl2K0/src/core.jl:123
│     [11] #invokelatest#2
│        @ ./essentials.jl:816 [inlined]
│     [12] invokelatest
│        @ ./essentials.jl:813 [inlined]
│     [13] handle_connection(f::Function, c::HTTP.Connections.Connection{Sockets.TCPSocket}, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Nothing)
│        @ HTTP.Servers /home/.julia/packages/HTTP/uAaAw/src/Servers.jl:447
│     [14] macro expansion
│        @ /home/.julia/packages/HTTP/uAaAw/src/Servers.jl:385 [inlined]
│     [15] (::HTTP.Servers.var"#16#17"{Oxygen.Core.var"#9#10"{Oxygen.Core.AutoDoc.var"#2#4"{Oxygen.Core.var"#28#31"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Vector{Function}}}, HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, Set{HTTP.Connections.Connection}, Int64, Nothing, Base.Semaphore, HTTP.Connections.Connection{Sockets.TCPSocket}})()
│        @ HTTP.Servers ./task.jl:514
└ @ HTTP.Servers /home/.julia/packages/HTTP/uAaAw/src/Servers.jl:461
```

Despite my efforts, I have been unable to identify the root cause of the ﻿IOError: write: broken pipe (EPIPE) error that occurs randomly when making requests to the API. I would greatly appreciate any insights or suggestions on how to resolve this issue.
As an additional note, I have observed that the error may occur more frequently when using threads for any parallelization within the API (running serve() not serveparallel()) or when the request is particularly long. However, it still happens randomly and without any consistent pattern.

**Comment by ndortega** [comment]
HI @BrandonEscamilla, 

I think this issue has been brought up before. It looks very similar to this issue: [broken pipe issue](https://github.com/ndortega/Oxygen.jl/issues/110#issuecomment-1539204751)

After checking it out, let me know if you have any follow-up questions about this!

**Comment by BrandonEscamilla** [comment]
Hi @ndortega, just wanted to provide an update regarding the issue we previously discussed. Although I initially thought that the session disconnection was related to the errors appearing in the logs, it turns out that it was just a coincidence. The disconnection was actually caused by a timeout in the cluster's load balancer. While this issue has been resolved, the errors are still persisting. Just wanted to clarify that the session disconnection was not directly related to the errors.

**Comment by ndortega** [comment]
Hi @BrandonEscamilla , 

Thanks for the clarification. Have you been able to address/pinpoint this issue? I plan on closing this issue unless we can find an Issue with the Oxygen.jl package.
