### ISSUE TITLE
How do I use server defined in a package?

### ISSUE THREAD

**Issue by asjir** [ndortega/Oxygen.jl#120]
I've created a [repo](xthttps://github.com/asjir/RouterDemo.jl/
) That just uses a [module from demo](https://github.com/ndortega/Oxygen.jl/blob/master/demo/routerdemo.jl)
I've tried `dev ...; using RouterDemo; serve()` and no routes get registered. 
On the other hand, if I copy [the main file](https://github.com/asjir/RouterDemo.jl/blob/main/src/RouterDemo.jl) from my package, into my terminal, and then `serve()` it works fine.
How do I fix this?

**Comment by ndortega** [comment]
Hi @asjir, 

Please take a look at this closed issue on the same topic. https://github.com/ndortega/Oxygen.jl/issues/115
It should have all the info you need to get your package working, please don't hesitate to let me know if you need any further clarification around this.

**Comment by asjir** [comment]
it's worked, thank you sm, I used the __init__ @eval method
