### ISSUE TITLE
Using request body in Swagger

### ISSUE THREAD

**Issue by DoktorMike** [ndortega/Oxygen.jl#121]
Awesome package. :)

Just tried to try out my POST  endpoint that should take a custom data format. It's not clear to me how to tell swagger to let me upload data when trying out the endpoint?

**Comment by ndortega** [comment]
Hi @DoktorMike, 

Thanks for the kind words, and I'm sorry about the long wait. 

Sadly, the built-in support for swagger generation is limited to path variables and request types. If you want to indicate other input types you can do any of the following:

- Manually write the schema yourself (use the `mergeschema()` function to update it in place)
- Use the SwaggerMarkdown library to add additional details to your endpoint.

Here's a link to the docs: 
- https://github.com/ndortega/Oxygen.jl#autogenerated-docs-with-swagger

This section shows examples of how to do both. Granted, you'll need to change the inputs to accept a file which is basically a base64-encoded string

Here's a good SO post that covers this schema: 
- https://stackoverflow.com/a/37932354/8364675

Here's the open-api 3.0.0 spec:
- https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#considerations-for-file-uploads

Let me know if you run into any issues or have any other questions. Additionally, If you give me a simple code snippet, I can update to show you how it's done
