### ISSUE TITLE
Using my own module that uses Oxygen

### ISSUE THREAD

**Issue by Sukhoverkhaya** [ndortega/Oxygen.jl#125]
Hi! I want to use my own module that uses Oxygen, but it dosen`t work if I "using MyOwnModule" without including file with its definition. I left a detailed description here in README-file: https://github.com/Sukhoverkhaya/OxygenExample.jl

**Comment by ndortega** [comment]
Hi @Sukhoverkhaya, 

Take a look at this thread, it looks like it's a similar issue: https://github.com/ndortega/Oxygen.jl/issues/115

**Comment by Sukhoverkhaya** [comment]
Thank you!
