### ISSUE TITLE
interpolation in endpoints

### ISSUE THREAD

**Issue by anandijain** [ndortega/Oxygen.jl#15]
```julia 
using Oxygen, HTTP
opd = Dict("plus" => +, "multiply" => *)
for (k, v) in opd
    @get "/$k/{a}/{b}" function (req, a, b)
        return v(parse(Float64, a), parse(Float64, b))
    end
end
```

```julia
ERROR: UndefVarError: k not defined
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Oxygen/twNox/src/Oxygen.jl:257 [inlined]
 [2] top-level scope
   @ REPL[12]:2
```

Thanks for this package, I really like the API. Usually I look at web things and cower in fear.
I haven't extensively looked into how hard it would be to make this work though. Thanks again

**Comment by ndortega** [comment]
@anandijain I like the Idea! Adding Interpolation would open up a bunch of interesting possibilities. I'm definitely gonna take a look into this. 

Thanks so much for your feedback, I really appreciate it!

**Comment by ndortega** [comment]
Hey @anandijain, it turns out it was easier than expected to get this feature built. It's been tested and merged into master. I'm gonna close out this issue. 

Once again, thanks for the great idea. Please feel free to open more
