### ISSUE TITLE
how about add jsonschema builtin?

### ISSUE THREAD

**Issue by yunfan** [ndortega/Oxygen.jl#31]
i had heard of this library from rss, and it really attracted me.

since its use JSON as the input and output type, its very suitable for those json api service
and there were a similar framework (fastify) in nodejs domain, i hope this library could add jsonschema builtin just like fastify

**Comment by ndortega** [comment]
At the moment, if you use the json() function to serialize json into a custom struct, it will actually throw an error if the json doesn't match it 100%. All properties must be present and have the correct types. In the meantime, you could very well use this to validate incoming data. 

Now regarding the return types - I'm actually in the process of adding auto-documentation to the code. So any defined request handlers will get parsed and converted into openApi 3.0 schema. The problem I'm facing now is that there is no way for users to easily define return type, description, and summary properties.

Adding some sort of helper function to register these additional properties would make it possible to add in some sort of validation layer later on (not to mention make the auto-generated docs more accurate). The only downside to adding a validation layer to the inputs and outputs would be performance. It would certainly be safer, but not faster (at least as far as I can see)

**Comment by yunfan** [comment]
well , there is a plugin for fastify (fastify-swagger) which will generate dynamic swagger api document automaticlly from its validation info, since you were working on this issue, i suggest to check fastify's validation , which also describe the return type

also a famouse feature provided by fastify is that its json serialize speed is faster than the JS's native JSON.stringify, because it use the validation info about return type, and 
generate the json string directly

**Comment by yunfan** [comment]
@ndortega jsonschema or other common serialization is ok. but native type might require the client of the web service createde by this framework to knew julia native type. which is not necessary i guess

**Comment by ndortega** [comment]
If we went down that route, we'd could convert the structs into jsonschema objects. Which we would use to validate incoming and outgoing data
