### ISSUE TITLE
CORS support would be great

### ISSUE THREAD

**Issue by nyjle** [ndortega/Oxygen.jl#35]
I've just started playing around with Oxygen and like it so far.  It would be super helpful if it supported CORS.

**Comment by ndortega** [comment]
At the moment there isn't built in support for cors, you have to create a custom function to intercept any preflight requests from the browser. There's an example in demo/main.jl on how to do this. Full disclosure, that example is based off the cors example in the HTTP.jl docs and I haven't added test cases for this feature.

Let me know if you run into any troubles/bugs setting it up.

I do see the merit in adding direct support for cors headers without having to create your own custom function. We could add either a new function to register cors headers or could even add a new argument to the `serve()` and `serveparallel()` functions to accept them.

**Comment by uvrey** [comment]
Thanks for this! I've just tried to serve using `serve(middleware=[CorsHandler])` but am receiving this error:

```ERROR: LoadError: MethodError: no method matching listen(::HTTP.Handlers.var"#4#5"{HTTP.Handlers.RequestHandlerFunction{Oxygen.ServerUtil.var"#5#7"}}, ::String, ::Int64; server::Sockets.TCPServer, middleware::Vector{typeof(Main.Main.CorsHandler)}, access_log::Oxygen.ServerUtil.var"#23#24")

Closest candidates are:
  listen(::Any, ::Union{String, Sockets.IPAddr}, ::Integer; sslconfig, tcpisvalid, server, reuseaddr, max_connections, connection_count, rate_limit, reuse_limit, readtimeout, verbose, access_log, on_shutdown) got unsupported keyword argument "middleware"
  ```
  
  Were you able to get CORS integrated like this?

**Comment by asjir** [comment]
I have no clue, works for me... do you get these versions?:
```
(...) pkg> status
Status `~/.../Project.toml`
  [cd3eb016] HTTP v1.10.1
  [df9a0d86] Oxygen v1.4.6
  ```

**Comment by uvrey** [comment]
> I have no clue, works for me... do you get these versions?:
> 
> ```
> (...) pkg> status
> Status `~/.../Project.toml`
>   [cd3eb016] HTTP v1.10.1
>   [df9a0d86] Oxygen v1.4.6
> ```

Thanks for the reply. Versions are the same on my side :)
