### ISSUE TITLE
Autogenerated Swagger docs only show the last method defined for a path.

### ISSUE THREAD

**Issue by wnoise** [ndortega/Oxygen.jl#65]
This happens in [`registerchema`](https://github.com/ndortega/Oxygen.jl/blob/6d4ac562c6889313d9793c59018aa189a40fd519/src/autodoc.jl#L370):
```
    schema["paths"][cleanedpath] = route 
```
which wholesale replaces any previous dictionary with the one generated here, which only has the current method defined.

I think the easiest fix is to merge any existing dictionary at schema["paths"][cleanedpath] into route before this.

**Comment by ndortega** [comment]
@wnoise Great catch! Thanks for reading through and finding the bug. I'll make sure to address this in the next patch
