### ISSUE TITLE
Broken on Julia v1.8

### ISSUE THREAD

**Issue by Octogonapus** [ndortega/Oxygen.jl#77]
The minimal example code from the documentation returns a 404 error when running on Julia v1.8. The `/docs` endpoint works. Running on Julia v1.6 works.

code:
```julia
using Oxygen
using HTTP

@get "/greet" function(req::HTTP.Request)
    return "hello world!"
end

# start the web server
serve()
```

server output:
```
[ Info: ✅ Started server: http://127.0.0.1:8080
[ Info: 📖 Documentation: http://127.0.0.1:8080/docs
[ Info: Listening on: 127.0.0.1:8080, thread id: 1
[ Info: 2022-12-21T19:41:35-0500 - 127.0.0.1:59706 - "GET /greet HTTP/1.1" 404
```

Request from Firefox:
```
GEThttp://127.0.0.1:8080/greet
[HTTP/1.1 404 Not Found 1413ms]

	
GET
	http://127.0.0.1:8080/greet
Status
404
Not Found
VersionHTTP/1.1
Transferred54 B (0 B size)
Request PriorityHighest

    	
    Transfer-Encoding
    	chunked
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    DNT
    	1
    Host
    	127.0.0.1:8080
    Sec-Fetch-Dest
    	document
    Sec-Fetch-Mode
    	navigate
    Sec-Fetch-Site
    	none
    Sec-Fetch-User
    	?1
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
```

**Comment by louis77** [comment]
I'm running Julia 1.8 with and your code works for me.

Have you tried to `update` you packages before?

**Comment by Octogonapus** [comment]
> Have you tried to update you packages before?

This happens even in a clean environment. Running v1.1.3.

**Comment by ndortega** [comment]
@Octogonapus 

Could you give me more details around your setup? I was able to run this example without any problems with 1.8.4 from my laptop (m1 mac)

<img width="929" alt="image" src="https://user-images.githubusercontent.com/22534471/211363560-f25bf265-5314-4ed2-958b-29c7c89f9050.png">

**Comment by Octogonapus** [comment]
The example code is working now for whatever reason :shrug: 
Not sure why it wasn't working in the first place.
