### ISSUE TITLE
Can't access Oxygen from Docker container 

### ISSUE THREAD

**Issue by Benvorth** [ndortega/Oxygen.jl#79]
If you run Oxygen `1.0.10` into a Docker container (Docker Desktop 4.15.0 (93002) on Windows 11)  and run it, the server will start up but you cannot access it on `localhost`. 

How to reproduce:

RestAPI.jl:

`

    module RestAPI
        using Oxygen, HTTP
        @get "/alive" function(req::HTTP.Request)
            @info "req: " req
            return html("Oxygen is alive")
        end
    end

    @info "Starting RestAPI..."
    RestAPI.runServer()
`

Dockerfile:

`

    FROM julia:1.8.3
    
    WORKDIR /root
    ADD / /root
    
    COPY . .
    
    COPY Manifest.toml .
    COPY Project.toml .
    RUN /usr/local/julia/bin/julia --project=. -e "using Pkg; Pkg.instantiate(); Pkg.precompile()"
    
    ENV JULIA_NUM_THREADS 2
    
    EXPOSE 8080
    ENTRYPOINT [ "julia", "--project=." ]

    CMD ["RestAPI.jl"]
`

Then build by `docker build -t ApiTest:latest .`

Then run: `docker run -p 8080:8080 -it --rm ApiTest:latest`

This gives:

`
    
    [ Info: Starting RestAPI...
       ____
      / __ \_  ____  ______ ____  ____ 
     / / / / |/_/ / / / __ `/ _ \/ __ \
    / /_/ />  </ /_/ / /_/ /  __/ / / /
    \____/_/|_|\__, /\__, /\___/_/ /_/ 
              /____//____/   
    
    [ Info: Starting server: http://127.0.0.1:8080
`

But if you try to `GET` `http://127.0.0.1:8080/alive` there is no result and no reaction in Oxygen's console.

**Comment by captchanjack** [comment]
Yeah I was seeing this too, found this post explaining in good detail https://discourse.julialang.org/t/difference-between-include-and-using/87795/4

Basically you need to load the routes at runtime, which is a bit strange to me

**Comment by Benvorth** [comment]
I am not sure if this is the problem here since the code runs without docker. So I guess it's not an issue with not loading the routes. 

Meanwhile I tried a different lib, too (`Genie.jl`). Here I observed the same behaviour. But in Genie I can modify not only the port but the host (nic) address` as well. Standard is `127.0.0.1`. If I modify this to `0.0.0.0` (= any address on that host) it works! So perhaps modifying `oxygen's` host IP, this would work as well?

Root case (as far as I explain it to myself) seems to be the `Docker Desktop` 's VM. `127.0.0.1` in there is not `localhost` on the Windows machine and seems to be no standard routes between them. You can connect in this VM from Windows from the command line running `wsl`. In there you can check the network config with `ifconfig`.

Conclusion: I think this issue can be closed. What do you think?

**Comment by BrandonEscamilla** [comment]
Yeah I just tried using serve(host="0.0.0.0") and it works @Benvorth

**Comment by Benvorth** [comment]
Great. Perhaps there should be a hint in the docs.
