### ISSUE TITLE
if you put it at the same time as JuliaWebAPI.jl, you will not be able to generate docs.

### ISSUE THREAD

**Issue by rtafds** [ndortega/Oxygen.jl#88]
After installing Oxygen.jl, I installed JuliaWebAPI.jl. Then, the dependence was broken, and docs was no longer generated.
What is the cause?
There is no inconvenience, but I wanted to know the cause.

**Comment by ndortega** [comment]
Hi @rtafds ,

This could be for a variety of reasons

- You weren't using Oxygen's routing macros which generate the open API docs for each attached route. 
- JuliaWebAPI might also use the default `/docs` or `/docs/schema` endpoints which is overwriting it. You could test this out by customizing the doc & schema endpoint. 

But to give you a better answer, you'd need to provide some sample code for me to look at. 

By the way, what's your use case? If you want to have functions that can be triggered via http requests then Oxygen is definitely a good choice, but if you need to trigger code via a message broker like ZMQ or RabbitMQ, you should probably just stick to JuliaWebAPI. I'm more intrigued why you feel the need to install both for a project, this could be a new use case I haven't thought of yet.

**Comment by ndortega** [comment]
Hi @rtafds,

I'm closing this since I haven't got a response in almost 2 months. If there is any bug that's come from this, feel free to open another issue
