### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by AndiLeni** [ndortega/Oxygen.jl#94]
Hello,
I have a usecase where a website requires updates over websocket.
Is an integration maybe planned for Oxygen?

As far as I have seen, HTTP.jl supports websockets, maybe Oxygen would benefit from a simple wrapper around this?

**Comment by ndortega** [comment]
Hi @AndiLeni , 

What kind of wrapper did you have in mind? I've used websockets on only a handful of occasions and so far I've been happy with how HTTP.jl does it. 

What would be the perfect wrapper to the websocket api? Below is an example of how to use it (taken from http.jl's docs)

```julia
# server
WebSockets.listen(host, port) do ws
    # iterate incoming websocket messages
    for msg in ws
        # send message back to client or do other logic here
        send(ws, msg)
    end
    # iteration ends when the websocket connection is closed by client or error
end 
```

**Comment by ndortega** [comment]
closing this issue due to no follow-up, feel free to reopen it.
